### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Effects/ShadowFX#1]
I would like to point out that an identifier like "[`__AMD_SHADOWFX_H__`](https://github.com/GPUOpen-Effects/ShadowFX/blob/2f4e9b3a4e660eed87a1823bceab40ea2779e12f/amd_shadowfx/inc/AMD_ShadowFX.h#L23)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jstewart-amd** [comment]
While double underscore is technically illegal, its use in libraries in commonplace. Still, we will consider changing our include guard naming convention. Thanks for the feedback.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?

Will it be better to keep this issue open until all affected components will be fixed?

**Comment by jstewart-amd** [comment]
Reopening this issue. A commit will soon be pushed to clean this up.

**Comment by elfring** [comment]
Thanks for [your improvement of affected identifiers](https://github.com/GPUOpen-Effects/ShadowFX/commit/3c30a78339571830ab276330adf92a939ec3665e).
